# Generated by Django 5.2.6 on 2025-10-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_phone_verified',
        ),
    ]
